# Generated by Django 2.2.5 on 2020-07-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200716_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='file',
            new_name='image_file',
        ),
    ]
